name: Monthly Docker Release

on:
  schedule:
    - cron: '40 5 1 * *' # on every first day of the month

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      id: prep
      run: |
          DOCKER_IMAGE=rabbitofcaerbannog/hackmyresume-builder
          MONTH_TAG=$(date +"%Y-%m")
          TAGS="${DOCKER_IMAGE}:${MONTH_TAG},${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}

    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.event_name == 'schedule' }}
        tags: ${{ steps.prep.outputs.tags }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
